Исправлены ошибка #15 Исправлены ошибка #16 Исправлены ошибка #17 Исправлены ошибка #18 Изменены комментарии к ошибкам при загрузке файлов через функцию load_file

diff --git a/src/pica b/src/pica
--- a/src/pica
+++ b/src/pica
@@ -13,7 +13,9 @@ echo_console() {
 }
 
 write_log() {
-  [ -n "${PICA_LOG_FILE}" ] && echo "$(date): ${*}" >> "${PICA_LOG_FILE}"
+  [ -e "${PICA_LOG_FILE}" -a ! -w "${PICA_LOG_FILE}" ] && return
+  [ ! -w "${PICA_LOG_FILE%/*}" ] && return
+  echo "$(date): ${*}" >> "${PICA_LOG_FILE}"
 }
 
 exit_error() {
@@ -43,8 +45,8 @@ save_report() {
 save_cache() {
   echo "CACHE_VERSION=\"${2}\"" > "${1}~" || exit_error "Write cache file ${1}~ failed"
   echo "CACHE_STATUS=\"${3}\"" >> "${1}~" || exit_error "Write cache file ${1}~ failed"
-  [ "${RESULT}" = 'OK' ] && COMMENT="${PA_COMMENT_OK}" || COMMENT="${PA_COMMENT_FAIL}"
-  echo "CACHE_COMMENT=\"${COMMENT}\"" >> "${1}~" || exit_error "Write cache file ${1}~ failed"
+  [ "${RESULT}" = 'OK' ] && local SC_COMMENT="${PA_COMMENT_OK}" || local SC_COMMENT="${PA_COMMENT_FAIL}"
+  echo "CACHE_COMMENT=\"${SC_COMMENT}\"" >> "${1}~" || exit_error "Write cache file ${1}~ failed"
   mv "${1}~" "${1}" || exit_error "Write cache file ${1} failed"
 }
 
@@ -55,7 +57,7 @@ load_file() {
     [ -z "${LINE}" -o "${LINE#\#}" != "${LINE}" ] && continue
     if [ "$(echo ${@} ${LINE%%=*} | tr ' ' '\n' | sort | uniq -d)" = "${LINE%%=*}" ]; then
       eval "${LINE%%=*}=${LINE#*=}"
-    else 
+    else
       echo "Error line: ${LINE}"  >&2
       return 1
     fi
@@ -87,14 +89,6 @@ while [ -n "${1}" ]; do
   shift
 done
 
-# проверка наличия папок cache и report
-if [ ! -d "/var/pica/cache" ]; then
-  mkdir "/var/pica/cache" || exit_error "Can not create /var/pica/cache"
-fi
-if [ ! -d "/var/pica/report" ]; then
-  mkdir "/var/pica/report" || exit_error "Can not create /var/pica/report"
-fi
-
 
 # проверка наличия conf файла
 [ -f "${CONF_FILE}" ] || exit_error "Conf file ${CONF_FILE} does not exist"
@@ -103,31 +97,43 @@ fi
 [ -r "${CONF_FILE}" ] || exit_error "/var/pica/cache""Can not read conf file ${CONF_FILE}"
 
 # загружаем из конфигурационного файла указанные опции
-load_file "${CONF_FILE}" PICA_TAGS PICA_TEST_DIR PICA_TEST_CACHE_DIR PICA_REPORT_DIR PICA_EXCEPTIONS PICA_LOG_FILE \
+load_file "${CONF_FILE}" PICA_TAGS PICA_TEST_DIR PICA_TEST_CACHE_DIR PICA_REPORT_DIR PICA_TEST_EXCLUDES PICA_LOG_FILE \
   || exit_error "Error loading config file ${CONF_FILE}"
 
 [ -z "${PICA_TAGS}" ] && exit_error "PICA_TAGS is not set in ${CONF_FILE}"
 [ -z "${PICA_TEST_DIR}" ] && exit_error "PICA_TEST_DIR is not set in ${CONF_FILE}"
 [ -z "${PICA_TEST_CACHE_DIR}" ] && exit_error "PICA_TEST_CACHE_DIR is not set in ${CONF_FILE}"
 [ -z "${PICA_REPORT_DIR}" ] && exit_error "PICA_REPORT_DIR is not set in ${CONF_FILE}"
-[ -z "${PICA_EXCEPTIONS}" ] && exit_error "PICA_EXCEPTIONS is not set in ${CONF_FILE}"
 [ -z "${PICA_LOG_FILE}" ] && exit_error "PICA_LOG_FILE is not set in ${CONF_FILE}"
 
 
-# проверка наличия папок cache и report
+# проверка наличия папок cache, report, log
 if [ ! -d "${PICA_TEST_CACHE_DIR}" ]; then
-    mkdir "${PICA_TEST_CACHE_DIR}" || exit_error "Can not create /var/pica/cache"
-  fi
-  if [ ! -d "${PICA_REPORT_DIR}" ]; then
-      mkdir "${PICA_REPORT_DIR}" || exit_error "Can not create /var/pica/report"
-    fi
+  mkdir -p "${PICA_TEST_CACHE_DIR}" || exit_error "Can not create ${PICA_TEST_CACHE_DIR}"
+fi
+if [ ! -d "${PICA_REPORT_DIR}" ]; then
+  mkdir -p "${PICA_REPORT_DIR}" || exit_error "Can not create ${PICA_REPORT_DIR}"
+fi
+if [ ! -d "${PICA_LOG_FILE%/*}" ]; then
+  mkdir -p "${PICA_LOG_FILE%/*}" || exit_error "Can not create ${PICA_LOG_FILE%/*}"
+fi
 
+# создание report файла если его не существует
+[ ! -w "${PICA_REPORT_DIR}" ] && exit_error "${PICA_REPORT_DIR} is not able to write"
 
 # проверка прав записи в лог файл
-  [ -w "${PICA_LOG_FILE}" ] || exit_error "${PICA_LOG_FILE} is not writable "
+if [ -e "${PICA_LOG_FILE}" ]; then
+  [ -w "${PICA_LOG_FILE}" ] || exit_error "${PICA_LOG_FILE} is not writable"
+else
+  [ -w "${PICA_LOG_FILE%/*}" -a -x "${PICA_LOG_FILE%/*}" ] || exit_error "${PICA_LOG_FILE%/*} is not writable"
+fi
 
 # проверка прав записи отчета
-  [ -w "${PICA_REPORT_DIR}/report" ] || exit_error "${PICA_REPORT_DIR}/report is not writable "
+if [ -e "${PICA_REPORT_DIR}/report" ]; then
+  [ -w "${PICA_REPORT_DIR}/report" ] || exit_error "${PICA_REPORT_DIR}/report is not writable"
+else
+  [ -w "${PICA_REPORT_DIR}" -a -x "${PICA_REPORT_DIR}" ] || exit_error "${PICA_REPORT_DIR} is not writable"
+fi
 
 # проверка наличия папки с тестами и возможности чтения
 [ -d "${PICA_TEST_DIR}" -a -r "${PICA_TEST_DIR}" -a -x "${PICA_TEST_DIR}" ] \
@@ -171,21 +177,22 @@ for TEST_FILE in "${PICA_TEST_DIR}"/*.pa; do
 
 
   load_file "${TEST_FILE}" PA_VERSION PA_TAG PA_COMMAND PA_COMMENT_OK PA_COMMENT_FAIL PA_EXPIRE PA_SEVERITY \
-    || exit_error "Error loading config file ${CONF_FILE}"
+    || exit_error "Error loading test file ${TEST_FILE}"
 
   [ -z "${PA_VERSION}" ] && echo "PA_VERSION is not exist in ${TEST_FILE}" >&2 && continue
   [ -z "${PA_TAG}" ] && echo "PA_TAG is not exist in ${TEST_FILE}" >&2 && continue
   [ -z "${PA_COMMAND}" ] && echo "PA_COMMAND is not exist in ${TEST_FILE}" >&2 && continue
-  [ -z "${PA_COMMENT_OK}" ] && echo "PA_COMMENT_OK is not exist in ${TEST_FILE}" >&2 && continue
   [ -z "${PA_COMMENT_FAIL}" ] && echo "PA_COMMENT_FAIL is not exist in ${TEST_FILE}" >&2 && continue
   [ -z "${PA_EXPIRE}" ] && echo "PA_EXPIRE is not exist in ${TEST_FILE}" >&2 && continue
   [ -z "${PA_SEVERITY}" ] && echo "PA_SEVERITY is not exist in ${TEST_FILE}" >&2 && continue
 
   # отсечение тестов с неудовлетворяющим тегом
-  [ -z "$(echo ${PICA_TAGS[@]} ${PA_TAG[@]} | tr ' ' '\n' | sort | uniq -d)" ] && continue
+  [ -z "$(echo ${PICA_TAGS} ${PA_TAG} | tr ' ' '\n' | sort | uniq -d)" ] && continue
 
   # исключение тестов по имени в глобальном конфиге
-  [ -n "$(echo ${PICA_EXCEPTIONS[@]} ${TEST_FILE##*/} | tr ' ' '\n' | sort | uniq -d)" ] && continue
+  if [ -n "${PICA_TEST_EXCLUDES}" ]; then
+    [ -n "$(echo ${PICA_TEST_EXCLUDES} ${TEST_FILE##*/} | tr ' ' '\n' | sort | uniq -d)" ] && continue
+  fi
 
   echo_console -n "${TEST_FILE##*/}... "
 
@@ -193,7 +200,7 @@ for TEST_FILE in "${PICA_TEST_DIR}"/*.pa; do
   if [ -e "${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache" ]; then
     # загрузка кеш файла
     load_file "${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache" CACHE_VERSION CACHE_STATUS CACHE_COMMENT \
-      || exit_error "Error loading config file ${CONF_FILE}"
+      || exit_error "Error loading cache file ${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache"
 
     # проверка кэша по EXPIRE
     LIFETIME_OF_CACHE=$[$(date +'%s')-$(stat -c '%Z' "${PICA_TEST_CACHE_DIR}/${TEST_FILE##*/}.cache")]
@@ -201,7 +208,7 @@ for TEST_FILE in "${PICA_TEST_DIR}"/*.pa; do
       echo_console -n 'cached '
       RESULT="${CACHE_STATUS}"
     fi
-  fi 
+  fi
 
   # выполняем тестирование, если кеш промах или кэш отсутствует
   if [ -z "${RESULT}" ]; then
@@ -218,17 +225,14 @@ for TEST_FILE in "${PICA_TEST_DIR}"/*.pa; do
   # создание статуса для отчета
   if [ "${RESULT}" = 'CRITICAL' ]; then
     let "REPORT_CRITICAL = REPORT_CRITICAL + 1"
-    COMMENT="${PA_COMMENT_FAIL}"
-    TEST_COMMENTS="${TEST_COMMENTS}${TEST_FILE##*/}: ${RESULT}: ${COMMENT}\n"
+    TEST_COMMENTS="${TEST_COMMENTS}${TEST_FILE##*/}: ${RESULT}: ${PA_COMMENT_FAIL}\n"
   elif [ "${RESULT}" = 'WARNING' ]; then
     let "REPORT_WARNING = REPORT_WARNING + 1"
-    COMMENT="${PA_COMMENT_FAIL}"
-    TEST_COMMENTS="${TEST_COMMENTS}${TEST_FILE##*/}: ${RESULT}: ${COMMENT}\n"
+    TEST_COMMENTS="${TEST_COMMENTS}${TEST_FILE##*/}: ${RESULT}: ${PA_COMMENT_FAIL}\n"
   else
     let "TOTAL_OK=TOTAL_OK+1"
-    COMMENT="${PA_COMMENT_OK}" 
   fi
-  
+
   let "TOTAL=TOTAL+1"
 done
 
